In [1]:
conda install numpy


Note: you may need to restart the kernel to use updated packages.



CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/win-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

'https//repo.anaconda.com/pkgs/main/win-64'




In [2]:
!pip install numpy

In [1]:
import numpy as np

In [6]:
# Conversion of list into an array

weight = [25,35,45,76,89,95]
 v
print('Type of weight',type(weight))

Array_weight = np.array(weight)
print('Type of Array Weight: ', type(Array_weight))

print(Array_weight)

Type of weight <class 'list'>
Type of Array Weight:  <class 'numpy.ndarray'>
[25 35 45 76 89 95]


In [7]:
Array_weight

array([25, 35, 45, 76, 89, 95])

In [10]:
print(Array_weight.size)
print(Array_weight.shape)

6
(6,)


In [11]:
import random as rn

#Random - random,randn,randint

np.random.random(size = 15)

#Uniform Distribution
#[0.0 - 1.00]
#0.0 - Inclusive,1.00 - Exclusive

array([0.91114552, 0.74312944, 0.7029137 , 0.7099826 , 0.63243727,
       0.5165845 , 0.96681542, 0.39030627, 0.89748343, 0.81270153,
       0.84513575, 0.7682866 , 0.89520711, 0.76926054, 0.82793585])

In [17]:
np.random.randn(5)

# Uniform Dist
# [0.0 - 1]
# 0 - Inclusive,1-Inclusive

array([-1.04774863, -1.63093359, -2.40105462, -0.95990578,  0.49665106])

In [18]:
np.random.randint(5,20) # 5 - 19 (random int numbers)

11

In [29]:
np.random.randint(5,50,5) #5-49-5
#5 la start aayu 50 la end aaganum,50 is exclusive,5 size la

array([49, 40, 14, 27, 23])

In [31]:
even_num = np.arange(start = 10,stop = 20,step=2)
even_num
#arange is a keyword as well as start stop step (Range here arange)

array([10, 12, 14, 16, 18])

In [255]:
# Linspace:

# Evenly Spaced ndarray Numbers
""" Even ah space aagum like 1.123456789,2.123456789"""
np.linspace(start=0,stop=50,num=10)


array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [247]:
# Creating 1D array filled with Zeros:
# 1D array mattum tha work aagum 
# Here 5 is Size
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [45]:
# Creating 1D array filled with Ones:
# 1D array mattum tha work aagum 

np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
# Empty Matrix:
# In Numpy Everything are keywords
# dtype means keyword for datatype
# 2d Array 

empty_matrix=np.empty((2,9), dtype = float)
empty_matrix

# Undefined arbitrary Values(uninitialized)

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.29061074e-306, 7.56587585e-307, 1.37961302e-306,
        1.05699242e-307, 8.01097889e-307, 1.78020169e-306],
       [7.56601165e-307, 1.02359984e-306, 1.33510679e-306,
        2.22522597e-306, 1.78019761e-306, 1.37962185e-306,
        1.78019625e-306, 8.34451928e-308, 2.22507386e-306]])

In [47]:
empty_matrix=np.empty((2,2), dtype = int)
empty_matrix


array([[ 1655285930, -1320766154],
       [  843568155,  -771794923]])

In [51]:
# String means Object
# 2d array
empty_matrix=np.empty((2,2), dtype = 'object')
empty_matrix

array([[None, None],
       [None, None]], dtype=object)

In [53]:
# FUll Matrix:
# SHIFT + TAB for Suggesitons
# Here 2 means 2 Rows and 4 MEANS columns
""" Fill_value na Namma enna value fill pannanum nu solramo it can be any 
number 2 or 3 or 4 or anything"""


np.full((2,4), fill_value=0)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [54]:
np.full((2,4), fill_value=4)

array([[4, 4, 4, 4],
       [4, 4, 4, 4]])

In [56]:
# Creating a Idenity Matrix
# Diagonal ah 1 varum
# for Eg 4 na 4 rows and 4 columns,5 na 5 rows 5 columns 

np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [57]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [67]:
# Eye

np.eye(N =3, M = 3, k= 0)


# K= 0 Represents Main Diagonal
# K > 0 Represents Upper Diagonal
# K < 0 Represents Lower Diagonal

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [68]:
np.eye(N =3, M = 3, k= 1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [69]:
np.eye(N =3, M = 3, k= -1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [72]:
names = ['Kavin','Prabhu','Vikas','Ravi']
print ('Student Name', type(names))

array_names=np.array(names)
print(array_names)

Student Name <class 'list'>
['Kavin' 'Prabhu' 'Vikas' 'Ravi']


In [84]:
# One Dimensional
one_dimensional = np.array([1,2,3,4,5,6,7,8])

print('Dimensions: ', one_dimensional.ndim)
print('Shape: ',one_dimensional.shape)
print('Size: ', one_dimensional.size)
print('Data Type: ',one_dimensional.dtype)

Dimensions:  1
Shape:  (8,)
Size:  8
Data Type:  int32


In [100]:
# Two Dimensional

two_dimensional = np.array([(1,2,3,4),(6,7,8,9),(2,3,5,8)])

print('Dimensions: ', two_dimensional.ndim)
print('Shape: ',two_dimensional.shape)
print('Size: ', two_dimensional.size)
print('Data Type: ',two_dimensional.dtype)

Dimensions:  2
Shape:  (3, 4)
Size:  12
Data Type:  int32


In [91]:
# Three Dimensional 
three_dimensional = np.array([(((1,2,3,4),(6,7,8,9),(2,3,5,8)))])

print('Dimensions: ', three_dimensionall.ndim)
print('Shape: ',three_dimensional.shape)
print('Size: ', three_dimensional.size)
print('Data Type: ',three_dimensional.dtype)

Dimensions:  3
Shape:  (1, 3, 4)
Size:  12
Data Type:  int32


In [101]:
# One Dimensional using String
one_dimensional = np.array(['kavin','ram','mohan'])

print('Dimensions: ', one_dimensional.ndim)
print('Shape: ',one_dimensional.shape)
print('Size: ', one_dimensional.size)
print('Data Type: ',one_dimensional.dtype)

Dimensions:  1
Shape:  (3,)
Size:  3
Data Type:  <U5


In [148]:
# Two Dimensional using String
two_dimensional = np.array([('kavin','ram','mohan','Ravi'),
                            ('kavin','ram','mohan','Ravi')])

print('Dimensions: ', two_dimensional.ndim)
print('Shape: ',two_dimensional.shape)
print('Size: ', two_dimensional.size)
print('Data Type: ',two_dimensional.dtype)

Dimensions:  2
Shape:  (2, 4)
Size:  8
Data Type:  <U5


In [103]:
# Three Dimensional using String
three_dimensional = np.array([((('kavin','ram','mohan'),
                                ('kavin','ram','mohan'),
                                ('kavin','ram','mohan')))])

print('Dimensions: ', three_dimensional.ndim)
print('Shape: ', three_dimensional.shape)
print('Size: ', three_dimensional.size)
print('Data Type: ',three_dimensional.dtype)

Dimensions:  3
Shape:  (1, 3, 3)
Size:  9
Data Type:  <U5


In [136]:
# Numpy in Array Methods:


original_array = np.array([(2,3),(5,6),(7,8)])
print('Original Array : \n', original_array)
print('Shape of Original Array: ', original_array.shape)
print("-------------------------------------------------------------")
print('\n')

reshaped_array = original_array.reshape(2,3)
print('Reshaped Array :\n', reshaped_array)
print('Shape of Reshaped Array : ',reshaped_array.shape)
print("-------------------------------------------------------------")



Original Array : 
 [[2 3]
 [5 6]
 [7 8]]
Shape of Original Array:  (3, 2)
-------------------------------------------------------------


Reshaped Array :
 [[2 3 5]
 [6 7 8]]
Shape of Reshaped Array :  (2, 3)
-------------------------------------------------------------


In [140]:
# Using Range

original_num = np.arange(20)
print('Original Number: ',original_num)
print('Shape of Original Number: ', original_num.shape)
print("-------------------------------------------------------------")

reshaped_num = original_num.reshape(10,2)
print('Reshaped number :', reshaped_num)
print('Shape of Reshaped number : ',reshaped_num.shape)




Original Number:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Shape of Original Number:  (20,)
-------------------------------------------------------------
Reshaped number : [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
Shape of Reshaped number :  (10, 2)


In [147]:
# Indexing in 1D Array

weight = np.array([45,55,88,99,63,46])

print('Indexing ; ' ,weight[0])
print('Indexing' ,weight[1])
print('Indexing' ,weight[2])

# How to Skip the Elements (By using :: two times naa 3 kudanum,three times
# na 4 kudukkanum because kadaisi exclusive epayume)
''' Because We said start from 1 '''
print('SKip ELements ',weight[1::2])





Indexing ;  45
Indexing 55
Indexing 88
SKip ELements  [55 99 46]


In [146]:
weight = np.array([(45,55),(88,99),(63,46)])

print('Indexing: ',weight[0:2])

Indexing:  [[45 55]
 [88 99]]


In [178]:
student = np.array([(10,20,30),(40,50,60),(70,80,90)])
print('Slicing :', student[1:2])



Slicing : [[40 50 60]]


In [187]:
student[2:4,2:3]

array([[90]])

In [196]:
# Take 50
student = np.array([(10,20,30),(40,50,60),(70,80,90)])

student[1:2,1:2]

array([[50]])

In [208]:
student_rollno = np.array([(1,2,3,4,5,6,7,8,9,10),
                                (11,12,13,14,15,16,17,18,19,20),
                                (21,22,23,24,25,26,27,28,29,30),
                                (31,32,33,34,35,36,37,38,39,40),
                                (41,42,43,44,45,46,47,48,49,50),
                                (51,52,53,54,55,56,57,58,59,60),
                                (61,62,63,64,65,66,67,68,69,70),
                                (71,72,73,74,75,76,77,78,79,80),
                                (81,82,83,84,85,86,87,88,89,90),
                                (91,92,93,94,95,96,97,98,99,100)
                                ])
print('Dimensions: ', student_rollno.ndim)

Dimensions:  2


In [217]:
student_rollno[8:9,7:8]

array([[88]])

In [224]:
# Comparison Operator
age = np.array([21,25,26,35,38,55,60,90,88])

print('Age : ',age[age>35])

Age :  [38 55 60 90 88]


In [245]:
# Arithmetic Operator
odd_numbers = np.array([1,3,5,7,9,11,13]) #1+2=3,3+4=7,5+6=11,7+8=15
even_numbers= np.array([2,4,6,8,10,12,14])
print('Summation :', odd_numbers+even_numbers)
print('Multiplication :', odd_numbers * even_numbers)
print('Division :', odd_numbers / even_numbers)
print('Exponential :', odd_numbers ** even_numbers)
print('Floor Division :', odd_numbers // even_numbers)



Summation : [ 3  7 11 15 19 23 27]
Multiplication : [  2  12  30  56  90 132 182]
Division : [0.5        0.75       0.83333333 0.875      0.9        0.91666667
 0.92857143]
Division : [          1          81       15625     5764801  -808182895 -1192716655
  -523170343]
Floor Division : [0 0 0 0 0 0 0]


In [3]:
age = np.array([21,25,26,35,38,55,60,90,88])

print('Age : ',age[age>=35])

Age :  [35 38 55 60 90 88]


In [14]:
# Two Dimension Array

num_matrix1 = np.array([[1,0,2],[4,-2,3]])
num_matrix2=np.array([[4,0],[2,3],[1,4]])
print(num_matrix1)
print(num_matrix2)

[[ 1  0  2]
 [ 4 -2  3]]
[[4 0]
 [2 3]
 [1 4]]


In [18]:
# .dot apdingaruthu 2 cross 3 ipdi irukaratha multiply pannum

a = num_matrix1.dot(num_matrix2)
print(a)

[[ 6  8]
 [15  6]]


In [19]:
age = np.array([25,35,97,89,21,27])
print('Minimum Age: ',age.min())

Minimum Age:  21


In [30]:
age = np.array([25,35,97,89,21,27])
print('Maximum Age: ',age.max())
print('Variance : ', age.var())
print('Standard Deviation : ', age.std())
print('Sum of all the Elements : ', age.sum())
print('Mean of All the Elements : ', age.mean())
print('Square : ', np.square(age))
print('Power : ', np.power(age, 3))

Maximum Age:  97
Variance :  990.6666666666666
Standard Deviation :  31.47485769096767
Sum of all the Elements :  294
Mean of All the Elements :  49.0
Square :  [ 625 1225 9409 7921  441  729]
Power :  [ 15625  42875 912673 704969   9261  19683]


In [35]:
# Transpose in 2 D 
matrix1 = np.array([[1,0,2],[4,-2,3]])
matrix2=np.array([[4,0],[2,3],[1,4]])
print(matrix1)
print(np.transpose(matrix1))

[[ 1  0  2]
 [ 4 -2  3]]
[[ 1  4]
 [ 0 -2]
 [ 2  3]]


In [36]:
# Concationation of 1 Dimensional Array

order1 = np.array([25,26,55,88,65])
order2= np.array([23,42,67,84,52])
order3= np.array([75,65,61,23,46])
np.concatenate([order1,order2,order3])

array([25, 26, 55, 88, 65, 23, 42, 67, 84, 52, 75, 65, 61, 23, 46])

In [54]:
#  concate Two DImensional 2 Cross 2:

odd_array= np.array([[1,3,5,7,9],[11,13,15,17,19]])
even_array = np.array([[2,4,6,8,10],[12,14,16,18,20]])


print('Row wise Concatenation : \n', 
      np.concatenate([odd_array, even_array]))
print('\n')
print('Column wise Concatenation : \n', 
      np.concatenate([odd_array, even_array], axis = 1))

Row wise Concatenation : 
 [[ 1  3  5  7  9]
 [11 13 15 17 19]
 [ 2  4  6  8 10]
 [12 14 16 18 20]]


Column wise Concatenation : 
 [[ 1  3  5  7  9  2  4  6  8 10]
 [11 13 15 17 19 12 14 16 18 20]]


In [66]:
# Concate Three Dimensional Array:

odd= np.array([[[1,3,5,7,9],[11,13,15,17,19]]])
even= np.array([[[2,4,6,8,10],[12,14,16,18,20]]])


print('Row wise Concatenation : \n', 
      np.concatenate([odd, even]))
print('\n')
print('Column wise Concatenation : \n', 
      np.concatenate([odd, even],axis=1))

Row wise Concatenation : 
 [[[ 1  3  5  7  9]
  [11 13 15 17 19]]

 [[ 2  4  6  8 10]
  [12 14 16 18 20]]]


Column wise Concatenation : 
 [[[ 1  3  5  7  9]
  [11 13 15 17 19]
  [ 2  4  6  8 10]
  [12 14 16 18 20]]]


# Two Dimensational
"""Stacking - IF we have 2 Dimensational Array
It will Convert into 3 Dimensational Array """

In [72]:
#Stacking
odd1 = np.array([[1,3],[5,7],[11,13],[15,17]])
even2 = np.array([[2,4],[6,8,],[12,14],[16,18]])


print('Stacking through Arrays : \n', np.stack([odd1, even2]))

print('Stacking and its Dimensions :\n ', 
      np.ndim(np.stack([odd1, even2], axis = 1)))

Stacking through Arrays : 
 [[[ 1  3]
  [ 5  7]
  [11 13]
  [15 17]]

 [[ 2  4]
  [ 6  8]
  [12 14]
  [16 18]]]
Stacking and its Dimensions :
  3


# HORIZONTAL STACK

In [73]:
# Horizontal ah Stack agum
lenovo = np.array([(1,3),(5,7)])
dell = ([(2,4),(6,8)])

print('Horizontal Stacking through Arrays : \n', np.hstack([lenovo, dell]))



Horizontal Stacking through Arrays : 
 [[1 3 2 4]
 [5 7 6 8]]


# Vertical Stacking

In [74]:
# Vertical ah Stack agum

lenovo = np.array([(1,3),(5,7)])
dell = ([(2,4),(6,8)])

print('Vertical Stacking through Arrays : \n', np.vstack([lenovo, dell]))

Vertical Stacking through Arrays : 
 [[1 3]
 [5 7]
 [2 4]
 [6 8]]


# Depth Wise Stacking

In [77]:
lenovo = np.array([(1,3),(5,7)])
dell = np.array([(2,4),(6,8)])

print('Depth Wise Stacking through Arrays : \n', np.dstack([lenovo, dell]))

Depth Wise Stacking through Arrays : 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Column Stack
Column Stack um Horizontal Stack um Onnu than

In [79]:
lenovo = np.array([(1,3),(5,7)])
dell = np.array([(2,4),(6,8)])

print('Column Stacking through Arrays : \n', np.column_stack([lenovo, dell])) 

Column Stacking through Arrays : 
 [[1 3 2 4]
 [5 7 6 8]]


In [81]:
m1 = np.zeros((2, 2))
m2 = np.ones((2, 2))
m3 = np.zeros((2, 2))
m4 = np.ones((2, 2))

a = np.block([[m1, m2], [m3, m4]])
a

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [82]:
m1 = np.zeros((2, 2))
m1

array([[0., 0.],
       [0., 0.]])

# Spliting 
- keyword split
- for arange 9 means split value should be equal

In [87]:
#Split:
one_d = np.arange(9)
var_1 = np.split(one_d,3)
var_1

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [34]:
#Dsplit_d 
# Dplit works only for 3 Dimensitional Array
ones= np.array([[[2,4,6,8,10],[2,4,5,6,7],[7,5,8,6,2]]])
var_2 = np.dsplit(ones,5)
print(var_2)


[array([[[2],
        [2],
        [7]]]), array([[[4],
        [4],
        [5]]]), array([[[6],
        [5],
        [8]]]), array([[[8],
        [6],
        [6]]]), array([[[10],
        [ 7],
        [ 2]]])]


In [37]:
# Flatten the Array
# It will output in a single line & Keyword is FLatten
char= np.array([[[2,4,6,8,10],[2,4,5,6,7],[7,5,8,6,2]]])
var_3 = char.flatten()
print(var_3)

[ 2  4  6  8 10  2  4  5  6  7  7  5  8  6  2]
